classroom/urls.py
from django.urls import path
from .views import (
    ClassListView,
    ClassCreateView,
    ClassDetailView,
    StudentClassDetail,
    RegisterListView,
    StudentRegisterClass,
    StudentClassListView,
    StudentDetail,
    SampleTemplateView,
    ClassDetailCreateView



)

app_name = 'classroom'



urlpatterns = [
    path('', ClassListView.as_view(), name='classroom'),
    path('create_class/', ClassCreateView.as_view(), name='create_class'),
    path('detail_class/<slug>/', ClassDetailView.as_view(), name='detail_class'),
    path('detail_register/<int:pk>/', StudentClassDetail.as_view(), name='detail_register'),
    path('register/', RegisterListView.as_view(), name='register'),
    path('register_student/', StudentRegisterClass.as_view(), name='student_register'),
    path('register_class/', StudentClassListView.as_view(), name='student_class'),
    path('student_detail/<slug>/', StudentDetail.as_view(), name='student_detail'),
    path('sample/', SampleTemplateView.as_view(), name='sample'),
    path('class_detail/', ClassDetailCreateView.as_view(), name='class_detail'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import account_view, teacher_view
# from account.views import logout_view, login_view
from django.conf import settings
from django.conf.urls.static import static
# from account.views import HomeView
from django.contrib.auth import views as auth_views
from account.views import LogoutConfirmView

urlpatterns = [
    path('admin/', admin.site.urls),


    path('account/', include('account.urls')),
    # path('account/', include('django.contrib.auth.urls')),
    # path('logout/', logout_view, name='logout'),
    # path('login/', login_view, name='login'),

    # path('accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/logout_confirm/', LogoutConfirmView.as_view(), name='logout_confirm'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_change/', auth_views.PasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('defupdate/', account_view, name='def-update'),

    path('users/', include('users.urls')),


    path('teacher/', include('teacher.urls')),
    path('classroom/', include('classroom.urls')),
    path('', include('course.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from . views import TodoListView, TodoCreateView
urlpatterns = [

    path('', TodoListView.as_view(), name='todo'),
    path('create/', TodoCreateView.as_view(), name='create'),

]

templates/base.html
{% bootstrap_css %}

{% load crispy_forms_tags %}
{% load static %}
{% load icons %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    {% block head %}{% endblock %}
{#    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">#}


    <link rel="stylesheet" type="text/css" href="{% static 'css/users/simple-sidebar.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.js" integrity="sha256-QWo7LDvxbWT2tbbQ97B53yJnYU3WhH/C8ycbRAkjPDc=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    <script type="text/javascript">
        var user = '{{ request.user }}'

        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = cookies[i].trim();
            {#// Does this cookie string begin with the name we want?#}
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getCookie('csrftoken');
        function csrfSafeMethod(method) {
            {#// these HTTP methods do not require CSRF protection#}
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });




    </script>

</head>

<body>


 <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-dark border-right" id="sidebar-wrapper">
        <div class="text-center">
            <div class="mt-3">
                <div class="profile-userpic">
                    <img src="{{ user.image.url }}" class="profile-img" alt="">
                </div>
            </div>
        </div>
    <div class="mt-3">
      <div class="list-group list-group-flush">
{#          <div class="mt-3">#}
              <a href="#" class="list-group-item list-group-item-action bg-dark text-light">Dashboard</a>
{#          </div>#}
          <div class="mt-1">
              <a href="{% url 'index' %}" class="list-group-item list-group-item-action bg-dark text-light">Home</a>
          </div>
              {% if user.is_student or user.is_superuser %}
                      <a href="{% url 'teacher' %}" class="list-group-item list-group-item-action bg-dark text-light">students</a>
              {% endif %}
          {% if user.is_teacher %}
          <a href="{% url 'classroom:create_class' %}" class="list-group-item list-group-item-action bg-dark text-light">teachers</a>
          {% endif %}
          {% if user.is_student %}
              <a href="#" class="list-group-item list-group-item-action bg-dark text-light">Your Course</a>
          {% endif %}
          <a href="{% url 'classroom:classroom' %}" class="list-group-item list-group-item-action bg-dark text-light">Class</a>
          <a href="{% url 'classroom:classroom' %}" class="list-group-item list-group-item-action bg-dark text-light">Approve</a>

      {% if user.is_superuser %}
          <a href="{% url 'classroom:register' %}" class="list-group-item list-group-item-action bg-dark text-light">Register</a>

      {% endif %}
          <a href="{% url 'classroom:student_register' %}" class="list-group-item list-group-item-action bg-dark text-light">Register_class</a>

          <a href="{% url 'classroom:student_class' %}" class="list-group-item list-group-item-action bg-dark text-light">Check_class</a>
      </div>
    </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">


      <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
          <button class="btn btn-primary" id="menu-toggle">{{ user.email }}</button>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                  <li class="nav-item active">
                      <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item">
                      {% if user.is_teacher or user.is_superuser %}
                          <a class="nav-link" href="{% url 'teacher' %}">MessageToStudent</a>
                          </li>
                      {% endif %}
                  {% if user.is_authenticated %}
                      <li class="nav-item dropdown">
                          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                              Account
                          </a>
                          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                              <a class="dropdown-item" href="{% url 'logout_confirm' %}">Logout</a>
                              <a class="dropdown-item" href="{% url 'update' user.pk %}">AccountUpdate</a>
                              <div class="dropdown-divider"></div>
                              <a class="dropdown-item" href="{% url 'password_change'  %}">PasswordChange</a>
                          </div>
                      </li>
                  {% endif %}
              </ul>
          </div>
      </nav>


        <div class="container-fluid">
{#            <div style="text-align: center">#}
                <div id="contents">
                    {% block content %}{% endblock %}
                </div>
{#            </div>#}
        </div>
    </div>
 </div>





  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>



 {% block javascripts %}{% endblock %}



</body>